# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json tsconfig.json ./
RUN npm install --ignore-scripts

# Copy source and sound files
COPY src ./src
COPY *.mp3 ./

# Build
RUN npm run build

# Runtime image
FROM node:lts-alpine
WORKDIR /app

# Copy built files and sound files
COPY --from=builder /app/build ./build
COPY --from=builder /app/*.mp3 ./
COPY --from=builder /app/node_modules ./node_modules

# Ensure execution bit
RUN chmod +x build/index.js

ENTRYPOINT ["node", "build/index.js"]
